import React, { createContext, useContext, useState } from "react";

// Create translation context
const TranslationContext = createContext<any>(null);

// Translation provider component
export const TranslationProvider: React.FC = ({ children }) => {
  // State to store the current language
  const [language, setLanguage] = useState("en");

  // Example translation data
  const translations = {
    en: {
      adminDashboard: "Admin Dashboard",
      dashboard: "Dashboard",
      humanResource: "Human Resource",
      milkParlor: "Milk Parlor",
      cowFeed: "Cow Feed",
      cowMonitor: "Cow Monitor",
      cowSale: "Cow Sale",
      farmExpense: "Farm Expense",
      suppliers: "Suppliers",
      manageCow: "Manage Cow",
      manageCowCalf: "Manage Cow Calf",
      manageStall: "Manage Stall",
      catalog: "Catalog",
      settings: "Settings",
      reports: "Reports",
      staffList: "Staff List",
      userList: "User List",
      employeeSalary: "Employee Salary",
      collectMilk: "Collect Milk",
      saleMilk: "Sale Milk",
      saleDueCollection: "Sale Due Collection",
      routineMonitor: "Routine Monitor",
      vaccineMonitor: "Vaccine Monitor",
      animalPregnancy: "Animal Pregnancy",
      saleList: "Sale List",
      expenseList: "Expense List",
      expensePurpose: "Expense Purpose",
      branch: "Branch",
      userType: "User Type",
      designation: "Designation",
      colors: "Colors",
      animalTypes: "Animal Types",
      vaccines: "Vaccines",
      foodUnit: "Food Unit",
      foodItem: "Food Item",
      monitoringServices: "Monitoring Services",
      totalStaff: "TOTAL STAFF",
      totalCow: "TOTAL COW",
      totalCalf: "TOTAL CALF",
      totalSupplier: "TOTAL SUPPLIER",
      totalCowStalls: "TOTAL COW STALLS",
      totalExpense: "TOTAL EXPENSE",
      totalCollectedMilk: "TOTAL COLLECTED MILK",
      totalSoldMilk: "TOTAL SOLD MILK",
      todayCollectedMilk: "TODAY COLLECTED MILK",
      todaySoldMilk: "TODAY SOLD MILK",
      todayCollectedMilkAmount: "TODAY COLLECTED MILK AMOUNT",
      todaySoldMilkAmount: "TODAY SOLD MILK AMOUNT",
      lastFiveExpenseHistory: "Last Five Expense History",
      date: "Date",
      amount: "Amount",
      jan082023: "Jan 08, 2023",
      nov292022: "Nov 29, 2022",
      jan282021: "Jan 28, 2021",
      mar242021: "Mar 24, 2021",
      feb282020: "Feb 28, 2020",
      shareProfit: "Share Profit",
      officeRent: "Office Rent",
      materials: "Materials",
      copyright: "Copyright @GesCow . All rights reserved ",
      LastFiveMilkSaleHistory: "Last Five Milk Sale History",
      CowFeedChart: "Cow Feed Chart",
      StallNumber: "Stall Number",
      Grass: "Grass",
      Salt: "Salt",
      Water: "Water",
      SetFeedChart: "Set Feed Chart",
      Gram: 'Gram',
    Time: 'Time',
    KG: 'KG',
    Stall: 'Stall',
    },
    fr: {
      adminDashboard: "Tableau de bord de l'administrateur",
      dashboard: "Tableau de bord",
      humanResource: "Ressources humaines",
      milkParlor: "Laiterie",
      cowFeed: "Alimentation des vaches",
      cowMonitor: "Surveillance des vaches",
      cowSale: "Vente de vaches",
      farmExpense: "Dépenses de ferme",
      suppliers: "Fournisseurs",
      manageCow: "Gérer les vaches",
      manageCowCalf: "Gérer les veaux",
      manageStall: "Gérer l'étable",
      catalog: "Catalogue",
      settings: "Paramètres",
      reports: "Rapports",
      staffList: "Liste du personnel",
      userList: "Liste des utilisateurs",
      employeeSalary: "Salaire des employés",
      collectMilk: "Collecte de lait",
      saleMilk: "Vente de lait",
      saleDueCollection: "Collection due à la vente",
      routineMonitor: "Surveillance de routine",
      vaccineMonitor: "Surveillance des vaccins",
      animalPregnancy: "Grossesse animale",
      saleList: "Liste de vente",
      expenseList: "Liste des dépenses",
      expensePurpose: "But des dépenses",
      branch: "Branche",
      userType: "Type d'utilisateur",
      designation: "Désignation",
      colors: "Couleurs",
      animalTypes: "Types d'animaux",
      vaccines: "Vaccins",
      foodUnit: "Unité alimentaire",
      foodItem: "Article alimentaire",
      monitoringServices: "Services de surveillance",
      totalStaff: "TOTAL PERSONNEL",
      totalCow: "TOTAL VACHE",
      totalCalf: "TOTAL VEAU",
      totalSupplier: "TOTAL FOURNISSEUR",
      totalCowStalls: "TOTAL BOX DE VACHE",
      totalExpense: "TOTAL DÉPENSE",
      totalCollectedMilk: "TOTAL LAIT COLLECTÉ",
      totalSoldMilk: "TOTAL LAIT VENDU",
      todayCollectedMilk: "LAIT COLLECTÉ AUJOURD'HUI",
      todaySoldMilk: "LAIT VENDU AUJOURD'HUI",
      todayCollectedMilkAmount: "MONTANT DE LAIT COLLECTÉ AUJOURD'HUI",
      todaySoldMilkAmount: "MONTANT DE LAIT VENDU AUJOURD'HUI",
      lastFiveExpenseHistory: "Derniers cinq historique des dépenses",
      date: "Date",
      amount: "Montant",
      jan082023: "8 janv. 2023",
      nov292022: "29 nov. 2022",
      jan282021: "28 janv. 2021",
      mar242021: "24 mars 2021",
      feb282020: "28 févr. 2020",
      shareProfit: "Partager les profits",
      officeRent: "Location de bureau",
      materials: "Matériaux",
      copyright: "Droits d'auteur @GesCow. Tous droits réservés ",
      LastFiveMilkSaleHistory: "Dernier historique des ventes de lait",
      CowFeedChart: "Graphique d'alimentation des vaches",
      StallNumber: "Numéro de l'étable",
      Grass: "Herbe",
      Salt: "Sel",
      Water: "Eau",
      SetFeedChart: "Définir le graphique d'alimentation",
      Quantity: 'Quantité',
    Gram: 'Gramme',
    Time: 'Temps',
    KG: 'KG',
    Stall: 'Étable',
    },
    ar: {
      adminDashboard: "لوحة القيادة للمشرف",
      dashboard: "لوحة القيادة",
      humanResource: "الموارد البشرية",
      milkParlor: "مزرعة الحليب",
      cowFeed: "تغذية البقر",
      cowMonitor: "مراقبة البقر",
      cowSale: "بيع البقر",
      farmExpense: "نفقات المزرعة",
      suppliers: "الموردين",
      manageCow: "إدارة البقر",
      manageCowCalf: "إدارة عجول البقر",
      manageStall: "إدارة المظال",
      catalog: "كتالوج",
      settings: "الإعدادات",
      reports: "تقارير",
      staffList: "قائمة الموظفين",
      userList: "قائمة المستخدمين",
      employeeSalary: "راتب الموظفين",
      collectMilk: "جمع الحليب",
      saleMilk: "بيع الحليب",
      saleDueCollection: "تحصيل مستحقات البيع",
      routineMonitor: "مراقبة الروتينية",
      vaccineMonitor: "مراقبة التطعيمات",
      animalPregnancy: "الحمل الحيواني",
      saleList: "قائمة المبيعات",
      expenseList: "قائمة المصروفات",
      expensePurpose: "غرض المصروفات",
      branch: "فرع",
      userType: "نوع المستخدم",
      designation: "التسمية",
      colors: "الألوان",
      animalTypes: "أنواع الحيوانات",
      vaccines: "اللقاحات",
      foodUnit: "وحدة الطعام",
      foodItem: "بند الطعام",
      monitoringServices: "خدمات المراقبة",
      totalStaff: "الموظفين الإجمالي",
      totalCow: "إجمالي البقر",
      totalCalf: "إجمالي العجول",
      totalSupplier: "إجمالي الموردين",
      totalCowStalls: "إجمالي أكوام البقر",
      totalExpense: "إجمالي المصروفات",
      totalCollectedMilk: "إجمالي الحليب المجموع",
      totalSoldMilk: "إجمالي الحليب المباع",
      todayCollectedMilk: "الحليب المجموع اليوم",
      todaySoldMilk: "الحليب المباع اليوم",
      todayCollectedMilkAmount: "مبلغ الحليب المجموع اليوم",
      todaySoldMilkAmount: "مبلغ الحليب المباع اليوم",
      lastFiveExpenseHistory: "تاريخ آخر خمسة مصروفات",
      date: "تاريخ",
      amount: "المبلغ",
      jan082023: "2023/1/8",
      nov292022: "2022/11/29",
      jan282021: "2021/1/28",
      mar242021: "2021/3/24",
      feb282020: " 2020/2/28  ",
      shareProfit: "مشاركة الأرباح",
      officeRent: "إيجار المكتب",
      materials: "مواد",
      copyright: "حقوق الطبع والنشر @GesCow. جميع الحقوق محفوظة ",
      LastFiveMilkSaleHistory: "تاريخ مبيعات الحليب الأخيرة",
      CowFeedChart: "رسم بياني لتغذية الأبقار",
      StallNumber: "رقم الحظيرة",
      Grass: "عشب",
      Salt: "ملح",
      Water: "ماء",
      SetFeedChart: "تعيين رسم بياني للتغذية",
      Quantity: 'الكمية',
    Gram: 'جرام',
    Time: 'وقت',
    KG: 'كيلوجرام',
    Stall: 'حظيرة',
    },
  };

  const translate = (key: string) => {
    return translations[language][key] || key;
  };
  // Value to provide to consumers of the translation context
  const value = {
    translate,
    setLanguage,
    language,
  };
  return (
    <TranslationContext.Provider value={value}>
      {children}
    </TranslationContext.Provider>
  );
};

// Custom hook to consume translation context
// eslint-disable-next-line react-refresh/only-export-components
export const useTranslation = () => {
  return useContext(TranslationContext);
};
